### ISSUE TITLE
Issues with swift-tools-version:5.2

### ISSUE THREAD

**Issue by daSkier** [twostraws/Sitrep#15]
I'm getting the following error when attempting to add Sitrep to my Package.swift: 
```
product 'Sitrep' not found. It is required by target 'App'.
```

This is my `Package.swift`:
```swift
// swift-tools-version:5.2
import PackageDescription

let package = Package(
    name: "PSVaporV4",
    platforms: [
       .macOS(.v10_15)
    ],
    dependencies: [
        // 💧 A server-side Swift web framework.
        .package(url: "https://github.com/vapor/vapor.git", from: "4.0.0-rc"),
...
        .package(url: "https://github.com/twostraws/Sitrep", .branch("master"))
    ],
    targets: [
    .target(name: "App", dependencies: [
...
        .product(name: "Sitrep", package: "Sitrep")
    ]),
    ],
       swiftLanguageVersions: [.v5]
)
```

I've had some other issues migrating to packages using swift-tools-version:5.2. Is there something I'm doing wrong here or do I need to make a change to accommodate this swift-tools-version? 

Edit: I know the package says it supports Swift 5.1, so if this just isn't supported in 5.2 that's totally fine. 

Thanks!

**Comment by twostraws** [comment]
I've bumped the whole thing up to Swift 5.3 now.
