### ISSUE TITLE
.sitrep.yml should not be required

### ISSUE THREAD

**Issue by twostraws** [twostraws/Sitrep#18]
We should assume sensible defaults instead.

**Comment by timfuqua** [comment]
So how do I get around this? I followed the install instructions that said:
```
git clone https://github.com/twostraws/Sitrep
cd Sitrep
make install
```

And then I ran:
```
sitrep --path ~/path/to/my/project/root --format json
```

And got this error:
```
Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “.sitrep.yml” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/TimFuqua/path/to/my/project/.sitrep.yml, NSUnderlyingError=0x7fb2bbc0ab90 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

So then I "touched" that file:
```
touch ~/path/to/my/project/.sitrep.yml
```

And tried again, and got this error:
```
sitrep --path ~/path/to/my/project --format json
Error: typeMismatch(Yams.Node.Mapping, Swift.DecodingError.Context(codingPath: [], debugDescription: "Expected to decode Mapping but found Node instead.", underlyingError: nil))
```

**Comment by Zedd0202** [comment]
@timfuqua Copy yml file(Hidden file) from Sitrep to my project.

@twostraws Hi. Can I ask a question?
I did it like @timfuqua 
But I got the following results

<img width="599" alt="스크린샷 2020-12-10 오후 9 09 54" src="https://user-images.githubusercontent.com/24826569/101770631-0dbcaa00-3b2c-11eb-8759-c9e9e47f1f36.png">

Am I using it right? 
I really want to use sitrep. Did I forget anything?
Can you give me any advice?

**Comment by rigovides** [comment]
Hi, I am having the same output as @Zedd0202. First I thought I needed to add more rules on the config files to include specific things with the project (such as the .xcproj file) but after checking at the Configuration role in the tool, I guess there's only configuration rules to exclude files. 

@twostraws Any pointers?

**Comment by rigovides** [comment]
@Zedd0202 I solved my issue by matching SwiftSintax version on Package.swift with my current swift tools version (In my case I was using Swift 5.3).

I created a small PR for updating the documentation as this issue might be pretty common nowdays XCode +12.3 is getting more used in prod environents: https://github.com/twostraws/Sitrep/pull/23

**Comment by twostraws** [comment]
.sitrep.yml is no longer required 🎉
