### ISSUE TITLE
Mint install fails

### ISSUE THREAD

**Issue by edi-medibank** [twostraws/Sitrep#21]
Installing via Mint now fails since it's expecting to clone "master" but now there is no such branch but "main" instead.

You can install if you specify the branch e.g:

`mint install twostraws/Sitrep@main`

**Comment by liamnichols** [comment]
Running the following:

```sh
$ mint run twostraws/Sitrep
```

Works fine now that there is a 1.0.0 tag:

```
🌱 Finding latest version of Sitrep
🌱 Cloning Sitrep 1.0.0
🌱 Resolving package
🌱 Building package
🌱 Installed Sitrep 1.0.0
```

So this issue can probably be closed 🙂

**Comment by twostraws** [comment]
Thank you for testing this out! 🙌
