### ISSUE TITLE
Publicise SitrepCore

### ISSUE THREAD

**Issue by Sherlouk** [twostraws/Sitrep#27]
Hey @twostraws 👋 

An awesome little tool that you've created here! I wonder if you'd be interesting in enabling SitrepCore as a product? 

It would allow other people's tools to build on top of the great stuff you've built as part of their own projects. Of course, you have the JSON output which could be used with ShellOut and some Codable stuff but this a lot more to manage (and introduces more routes for problems) versus using the library directly.

In theory it would just be a case of adding the product to the Package.swift and making a couple extra things public!

**Comment by twostraws** [comment]
PRs most welcome!

**Comment by Sherlouk** [comment]
Awesomeeeee 🙌🏼

I'll get on that 🤓
