### ISSUE TITLE
Fails to work with Version 13.3 (13E113)

### ISSUE THREAD

**Issue by Waxhaw** [twostraws/Sitrep#33]
~/Library/org.swift.swiftpm/collections.json has been deprecated. Please delete it and use the new ~/Library/org.swift.swiftpm/configuration/collections.json instead.
error: Could not find Package.swift in this directory or any of its parent directories.

Followed the steps to setup and install and got the error above.

Fingers crossed that changing the json fixes my issues.  Just posting so folks are aware of changes in Xcode.

**Comment by Waxhaw** [comment]
So if you crack that open to see the issue, it points to:  https://developer.apple.com/swift/packages/collections/apple.json

I'm at a loss as to what is causing this issue now.

**Comment by twostraws** [comment]
I've now updated Sitrep to work with the latest Xcode release, so I'm closing this. Thank you!
