### ISSUE TITLE
Tagged release?

### ISSUE THREAD

**Issue by goranmoomin** [twostraws/Sitrep#6]
I would like to make a [Homebrew](https://brew.sh) formula from Sitrep, but one of the requirements for all formulas in the [main tap](https://github.com/Homebrew/homebrew-core) is that [it should have a stable, tagged version](https://docs.brew.sh/Formula-Cookbook#basic-instructions). Is there any plans for releases?

**Comment by twostraws** [comment]
This has now been done, and there is also a Homebrew formula. Use `brew install twostraws/brew/sitrep` to install.
